model_type: MI_HGNN
spec_type: BHMG
robot_type: UNITREE_G1_29DOF
output_type: CENTER_OF_MASS
symmetry_type: C2
parser_path: src/graph/parser/usd/g1_29dof_rev_1_0.usd
dataset_path: src/data/dataset/datasets_memmap/g1_locomotion_memmap_20260314_102929
val_split_ratio: 0.2
batch_size: 128
num_workers: 4
history_length: 150
hidden_channels: 128
num_layers: 3
activation: ReLU
optimizer: Adam
max_epochs: 10
learning_rate: 0.0003
accelerator: gpu
precision: 32-true
robot_mass: 35.0
foot_contact_area: 0.01400
