model_type: MS_HGNN
spec_type: QHMG
robot_type: UNITREE_GO2
output_type: CONTACT
symmetry_type: K4
parser_path: src/graph/parser/usd/go2.usd
dataset_path: src/data/dataset/datasets_memmap/go2_locomotion_memmap_20260314_103007
val_split_ratio: 0.2
batch_size: 128
num_workers: 4
history_length: 150
hidden_channels: 128
num_layers: 3
activation: ReLU
optimizer: Adam
max_epochs: 10
learning_rate: 0.0003
accelerator: gpu
precision: 32-true
robot_mass: 12.0
foot_contact_area: 0.0015