from abc import ABC, abstractmethod
import random
from typing import Any, Self, cast

import torch
from torch_geometric.data import Batch  # type: ignore

from src.config.batch_schema import HeteroDataBatch
from src.config.train_enum import SymmetryType
from src.graph.feature.base_feature import BaseFeatureType
from src.graph.spec.base_spec import (
    symmetry_edge_dict_type,
    symmetry_permutation_dict_type,
)

FEATURE_TYPE_WIDTH: dict[BaseFeatureType, int] = {
    BaseFeatureType.SCALAR: 1,
    BaseFeatureType.VECTOR_3D: 3,
    BaseFeatureType.PSEUDOVECTOR_3D: 3,
}

OUTPUT_LABEL_LAYOUT: dict[str, tuple[str, list[BaseFeatureType]]] = {
    "y_contact": ("foot", [BaseFeatureType.SCALAR]),
    "y_ground_reaction_force": ("foot", [BaseFeatureType.VECTOR_3D]),
    "y_base_velocity": (
        "base",
        [BaseFeatureType.VECTOR_3D, BaseFeatureType.PSEUDOVECTOR_3D],
    ),
    "y_total_ground_reaction_force": ("base", [BaseFeatureType.VECTOR_3D]),
    "y_base_angular_acceleration": ("base", [BaseFeatureType.PSEUDOVECTOR_3D]),
    "y_joint_acceleration": ("joint", [BaseFeatureType.SCALAR]),
    "y_joint_friction": ("joint", [BaseFeatureType.SCALAR]),
}


class BaseSymmetry(ABC):
    _registry: dict[SymmetryType, Self] = {}

    def __init__(self):
        super().__init__()

    @classmethod
    def register(cls, symmetry_type: SymmetryType):
        """
        Decorator to register a symmetry implementation for a given symmetry type.
        """

        def decorator(symmetry_cls: Self) -> Self:
            cls._registry[symmetry_type] = symmetry_cls
            return symmetry_cls

        return decorator

    @classmethod
    def create_symmetry(
        cls,
        symmetry_type: SymmetryType,
        symmetry_edge_dict: symmetry_edge_dict_type,
        symmetry_permutation_dict: symmetry_permutation_dict_type | None = None,
    ) -> Self:
        """
        Factory method to create a symmetry instance based on the symmetry type.
        """
        if symmetry_type not in cls._registry:
            raise ValueError(f"Symmetry for type '{symmetry_type}' is not registered.")
        symmetry_cls = cls._registry[symmetry_type]
        return symmetry_cls.build_from(symmetry_edge_dict, symmetry_permutation_dict)

    @classmethod
    @abstractmethod
    def build_from(
        cls,
        symmetry_edge_dict: symmetry_edge_dict_type,
        symmetry_permutation_dict: symmetry_permutation_dict_type | None = None,
    ) -> Self:
        """
        Abstract method to build a symmetry instance from configuration or defaults.
         This method should be implemented by each concrete symmetry class to handle
         any specific initialization logic required for that symmetry.
        """
        pass

    @abstractmethod
    def expand_data(self, data_list: list[HeteroDataBatch]) -> list[HeteroDataBatch]:
        """
        Expand input batch according to the symmetry defined by this class.

        INPUT:
        - data_list: list of input data batches containing node features, edge features, etc.

        OUTPUT:
        - expanded_data_list: new list where each data batch has been duplicated and transformed
          according to the symmetry (e.g., for K4, we would create 4 copies of each
          limb with appropriate transformations to represent front/back + left/right
          + rotational symmetry).
        """
        pass

    def generate_combination(
        self, symmetry_edge_types: dict[str, list[int]]
    ) -> list[tuple[str, ...]]:
        """
        Generate combinations of edge types for symmetry transformations.

        This method should create the necessary combinations of edge types that need to be
        transformed according to the specific symmetry. For example, if we have edges connecting left
        and right limbs, we would generate pairs of edge types that need to be swapped or
        transformed.

        INPUT:
        - symmetry_edge_types: dict of symmetry edge type names and their associated weights that are relevant for the symmetry

        OUTPUT:
        - combination: list of tuples where each tuple contains a combination of symmetry edge types that
          should be transformed together according to the symmetry.
        """
        from itertools import chain, combinations

        s = list(symmetry_edge_types.keys())
        return list(chain.from_iterable(combinations(s, r) for r in range(len(s) + 1)))

    def generate_reflection_coefficients(
        self, symmetry_edge_types: dict[str, list[int]]
    ) -> dict[tuple[str, str], tuple[int, int, int]]:
        """
        Generate reflection coefficients for each combination of edge types.

        This method should create a mapping from each combination of edge types (as generated by
        generate_combination) to a reflection coefficient that indicates how the features should be
        transformed (e.g., multiplied by -1 for certain features when reflecting across a plane).

        INPUT:
        - symmetry_edge_types: dict of symmetry edge type names and their associated weights that are relevant for the symmetry

        OUTPUT:
        - reflection_coefficients: dict mapping from combination of symmetry edge types to reflection
          coefficient (e.g., 1.0 for no change, -1.0 for reflection).
        """
        reflection_coefficients: dict[tuple[str, str], tuple[int, int, int]] = {}

        for sym_edge_type, axes_to_flip in symmetry_edge_types.items():

            # Vectors: flip the axes being reflected
            vector_coeff = self._coefficients_from_axes(
                axes_to_flip, BaseFeatureType.VECTOR_3D
            )
            reflection_coefficients[
                (sym_edge_type, BaseFeatureType.VECTOR_3D.value)
            ] = vector_coeff

            # Pseudovectors: flip the PERPENDICULAR axes (not the reflection axis)
            pseudovector_coeff = self._coefficients_from_axes(
                axes_to_flip, BaseFeatureType.PSEUDOVECTOR_3D
            )
            reflection_coefficients[
                (sym_edge_type, BaseFeatureType.PSEUDOVECTOR_3D.value)
            ] = pseudovector_coeff

            scalar_coeff = self._coefficients_from_axes(
                axes_to_flip, BaseFeatureType.SCALAR
            )
            reflection_coefficients[(sym_edge_type, BaseFeatureType.SCALAR.value)] = (
                scalar_coeff
            )

        return reflection_coefficients

    def _coefficients_from_axes(
        self, axes_to_flip: list[int], feature_type: BaseFeatureType
    ) -> tuple[int, int, int]:
        """
        Generate reflection coefficients for a given feature type based on the axes to flip.

        For vectors:
        - If an axis is flipped, the coefficient for that axis is -1, otherwise it's 1.

        For pseudovectors:
        - If an axis is flipped, the coefficient for the perpendicular axes is -1, and the flipped axis is 1.

        For scalars:
        - Coefficients are always (1, 1, 1) since scalars do not change under reflection.

        INPUT:
        - axes_to_flip: list of axis indices that are flipped (e.g., [0] for x-axis)
        - feature_type: type of feature (VECTOR_3D, PSEUDOVECTOR_3D, SCALAR)

        OUTPUT:
        - Tuple of reflection coefficients for (x, y, z) axes
        """
        vector_coeff = [1, 1, 1]
        for axis in axes_to_flip:
            if axis < 0 or axis > 2:
                raise ValueError(f"Invalid axis {axis}. Must be 0, 1, or 2.")
            vector_coeff[axis] *= -1

        if feature_type == BaseFeatureType.VECTOR_3D:
            return (vector_coeff[0], vector_coeff[1], vector_coeff[2])
        if feature_type == BaseFeatureType.PSEUDOVECTOR_3D:
            determinant = -1 if (len(axes_to_flip) % 2 == 1) else 1
            pseudo = [determinant * value for value in vector_coeff]
            return (pseudo[0], pseudo[1], pseudo[2])
        return (1, 1, 1)

    def _resolve_group_permutation(
        self,
        node_type: str,
        sym_edge_type: str,
    ) -> list[int] | None:
        """
        Resolve group-level permutation from spec-provided mapping.
        """
        permutation_cfg = getattr(self, "symmetry_permutation", None)
        if permutation_cfg is None:
            return None
        node_mapping = permutation_cfg.get(node_type)
        if node_mapping is None:
            return None
        group_perm = node_mapping.get(sym_edge_type)
        if group_perm is None or len(group_perm) == 0:
            return None
        if len(set(group_perm)) != len(group_perm):
            return None
        if min(group_perm) < 0 or max(group_perm) >= len(group_perm):
            return None
        return group_perm

    def _group_row_permutation_indices(
        self,
        num_rows: int,
        group_permutation: list[int],
    ) -> list[int]:
        """
        Build row permutation indices from a group permutation specification.

        Assumes rows are grouped per group in contiguous blocks and preserves
        within-group offsets.
        """
        if num_rows <= 1:
            return list(range(num_rows))

        group_count = len(group_permutation)
        if group_count <= 0:
            return list(range(num_rows))
        if num_rows % group_count != 0:
            return list(range(num_rows))

        rows_per_group = num_rows // group_count

        permutation: list[int] = []
        for target_group in group_permutation:
            start = target_group * rows_per_group
            end = start + rows_per_group
            permutation.extend(range(start, end))
        return permutation

    def apply_row_permutation(
        self,
        tensor: torch.Tensor,
        node_type: str,
        sym_edge_type: str,
    ) -> torch.Tensor:
        """
        Apply one symmetry row permutation to a node-feature tensor.
        """
        if tensor.ndim != 2:
            return tensor
        group_permutation = self._resolve_group_permutation(node_type, sym_edge_type)
        if group_permutation is None:
            return tensor
        permutation = self._group_row_permutation_indices(
            tensor.shape[0], group_permutation
        )
        if len(permutation) != tensor.shape[0]:
            return tensor
        idx = torch.tensor(permutation, device=tensor.device, dtype=torch.long)
        return tensor.index_select(0, idx)

    def apply_row_permutation_combo(
        self,
        tensor: torch.Tensor,
        node_type: str,
        combo: tuple[str, ...],
    ) -> torch.Tensor:
        """
        Apply a sequence of row permutations, one per symmetry operator.
        """
        transformed = tensor
        for sym_edge_type in combo:
            transformed = self.apply_row_permutation(
                transformed,
                node_type,
                sym_edge_type,
            )
        return transformed

    def _output_permutation_indices(
        self,
        node_type: str,
        combo: tuple[str, ...],
        output_count: int,
    ) -> list[int]:
        indices = list(range(output_count))
        for sym_edge_type in combo:
            group_permutation = self._resolve_group_permutation(
                node_type, sym_edge_type
            )
            if group_permutation is None:
                continue
            row_permutation = self._group_row_permutation_indices(
                output_count,
                group_permutation,
            )
            if len(row_permutation) != output_count:
                continue
            indices = [indices[i] for i in row_permutation]
        return indices

    def apply_output_permutation(
        self,
        tensor: torch.Tensor,
        node_type: str,
        combo: tuple[str, ...],
    ) -> torch.Tensor:
        if tensor.ndim == 1:
            permutation = self._output_permutation_indices(
                node_type, combo, int(tensor.shape[0])
            )
            idx = torch.tensor(permutation, device=tensor.device, dtype=torch.long)
            return tensor.index_select(0, idx)

        if tensor.ndim == 2:
            if tensor.shape[0] == 1:
                permutation = self._output_permutation_indices(
                    node_type, combo, int(tensor.shape[1])
                )
                idx = torch.tensor(permutation, device=tensor.device, dtype=torch.long)
                return tensor.index_select(1, idx)
            permutation = self._output_permutation_indices(
                node_type, combo, int(tensor.shape[0])
            )
            idx = torch.tensor(permutation, device=tensor.device, dtype=torch.long)
            return tensor.index_select(0, idx)

        if tensor.ndim == 3 and tensor.shape[0] == 1:
            permutation = self._output_permutation_indices(
                node_type, combo, int(tensor.shape[1])
            )
            idx = torch.tensor(permutation, device=tensor.device, dtype=torch.long)
            return tensor.index_select(1, idx)

        return tensor

    def parse_feature_type_layout(
        self,
        serialized_layout: dict[str, list[tuple[int, int, str]]] | None,
    ) -> dict[str, list[tuple[int, int, BaseFeatureType]]]:
        if serialized_layout is None:
            return {}
        parsed: dict[str, list[tuple[int, int, BaseFeatureType]]] = {}
        for node_type, blocks in serialized_layout.items():
            parsed[node_type] = [
                (int(start), int(end), BaseFeatureType(feature_type))
                for start, end, feature_type in blocks
            ]
        return parsed

    def infer_feature_type_layout(
        self,
        x_dict: dict[str, Any],
    ) -> dict[str, list[tuple[int, int, BaseFeatureType]]]:
        inferred: dict[str, list[tuple[int, int, BaseFeatureType]]] = {}
        for node_type, tensor in x_dict.items():
            if tensor.ndim != 2:
                continue
            feature_dim = int(tensor.shape[1])
            if feature_dim >= 10:
                inferred[node_type] = [
                    (0, 4, BaseFeatureType.SCALAR),
                    (4, 7, BaseFeatureType.VECTOR_3D),
                    (7, 10, BaseFeatureType.PSEUDOVECTOR_3D),
                ]
            elif feature_dim >= 6:
                inferred[node_type] = [
                    (0, 3, BaseFeatureType.VECTOR_3D),
                    (3, 6, BaseFeatureType.PSEUDOVECTOR_3D),
                ]
            else:
                inferred[node_type] = [(0, feature_dim, BaseFeatureType.SCALAR)]
        return inferred

    @staticmethod
    def _expand_blocks_for_feature_dim(
        blocks: list[tuple[int, int, BaseFeatureType]],
        feature_dim: int,
    ) -> list[tuple[int, int, BaseFeatureType]]:
        """Repeat a single-step layout across stacked history slices."""
        if not blocks:
            return blocks
        layout_width = max(end for _, end, _ in blocks)
        if layout_width <= 0 or feature_dim <= layout_width:
            return blocks
        if feature_dim % layout_width != 0:
            return blocks
        repeats = feature_dim // layout_width
        expanded: list[tuple[int, int, BaseFeatureType]] = []
        for slice_idx in range(repeats):
            offset = slice_idx * layout_width
            expanded.extend(
                (start + offset, end + offset, feature_type)
                for start, end, feature_type in blocks
            )
        return expanded

    def _combo_coefficients(
        self,
        combo: tuple[str, ...],
        feature_type: BaseFeatureType,
    ) -> torch.Tensor:
        """Compose per-operator reflection coefficients for a feature type."""
        coefficients = torch.ones(3, dtype=torch.float32)
        for sym_edge_type in combo:
            axes_to_flip = self.symmetry_edge_types[sym_edge_type]
            edge_coefficients = torch.tensor(
                self._coefficients_from_axes(axes_to_flip, feature_type),
                dtype=torch.float32,
            )
            coefficients = coefficients * edge_coefficients
        return coefficients

    def transform_x_dict(
        self,
        x_dict: dict[str, Any],
        serialized_layout: dict[str, list[tuple[int, int, str]]] | None,
        combo: tuple[str, ...],
    ) -> dict[str, torch.Tensor]:
        """Permute node rows and reflect component blocks under a symmetry combo."""
        parsed_layout = self.parse_feature_type_layout(serialized_layout)
        if not parsed_layout:
            parsed_layout = self.infer_feature_type_layout(x_dict)

        transformed_x_dict: dict[str, torch.Tensor] = {}
        for node_type, x in x_dict.items():
            if not isinstance(x, torch.Tensor) or x.ndim != 2:
                transformed_x_dict[node_type] = x
                continue

            blocks = parsed_layout.get(node_type)
            if blocks is None:
                blocks = self.infer_feature_type_layout({node_type: x}).get(
                    node_type, []
                )
            blocks = self._expand_blocks_for_feature_dim(blocks, int(x.shape[1]))

            transformed = self.apply_row_permutation_combo(
                x.clone(), node_type, combo
            )
            for start, end, feature_type in blocks:
                if end <= start or feature_type == BaseFeatureType.SCALAR:
                    continue
                width = end - start
                if width % 3 != 0:
                    continue
                coefficients = self._combo_coefficients(combo, feature_type).to(
                    device=x.device, dtype=x.dtype
                )
                for offset in range(start, end, 3):
                    transformed[:, offset : offset + 3] = (
                        transformed[:, offset : offset + 3] * coefficients
                    )

            transformed_x_dict[node_type] = transformed

        return transformed_x_dict

    def _transform_label_rows(
        self,
        rows: torch.Tensor,
        node_type: str,
        combo: tuple[str, ...],
    ) -> torch.Tensor:
        permutation = self._output_permutation_indices(
            node_type, combo, int(rows.shape[0])
        )
        index = torch.tensor(permutation, device=rows.device, dtype=torch.long)
        return rows.index_select(0, index)

    def _transform_label_blocks(
        self,
        rows: torch.Tensor,
        feature_types: list[BaseFeatureType],
        combo: tuple[str, ...],
    ) -> torch.Tensor:
        offset = 0
        for feature_type in feature_types:
            width = FEATURE_TYPE_WIDTH[feature_type]
            if feature_type != BaseFeatureType.SCALAR and width == 3:
                coefficients = self._combo_coefficients(combo, feature_type).to(
                    device=rows.device, dtype=rows.dtype
                )
                rows[:, offset : offset + 3] = rows[:, offset : offset + 3] * coefficients
            offset += width
        return rows

    def transform_label(
        self,
        tensor: torch.Tensor,
        node_type: str,
        feature_types: list[BaseFeatureType],
        combo: tuple[str, ...],
    ) -> torch.Tensor:
        """Apply the same row permutation and reflections as the node features."""
        width = sum(FEATURE_TYPE_WIDTH[feature_type] for feature_type in feature_types)
        if width <= 0:
            return tensor

        if tensor.ndim == 1:
            node_count = int(tensor.shape[0]) // width
            if node_count * width != int(tensor.shape[0]) or node_count <= 0:
                return tensor
            rows = tensor.reshape(node_count, width).clone()
            rows = self._transform_label_rows(rows, node_type, combo)
            rows = self._transform_label_blocks(rows, feature_types, combo)
            return rows.reshape(tensor.shape)

        if tensor.ndim == 2 and tensor.shape[0] == 1:
            dim = int(tensor.shape[1])
            node_count = dim // width
            if node_count * width != dim or node_count <= 0:
                return tensor
            rows = tensor.reshape(node_count, width).clone()
            rows = self._transform_label_rows(rows, node_type, combo)
            rows = self._transform_label_blocks(rows, feature_types, combo)
            return rows.reshape(tensor.shape)

        return tensor

    def sample_combo(self) -> tuple[str, ...]:
        """Sample one group element (including identity) for augmentation."""
        combination = getattr(self, "combination", None)
        if not combination:
            return ()
        return random.choice(combination)

    def apply_symmetry_transform(
        self,
        data: HeteroDataBatch,
        combo: tuple[str, ...],
    ) -> HeteroDataBatch:
        """Transform node features and all available labels consistently."""
        new_data = data.clone()
        serialized_layout = getattr(data, "feature_type_layout", None)
        new_data.x_dict = self.transform_x_dict(
            data.x_dict, serialized_layout, combo
        )

        for label_key, (node_type, feature_types) in OUTPUT_LABEL_LAYOUT.items():
            if not hasattr(new_data, label_key):
                continue
            transformed_label = self.transform_label(
                getattr(new_data, label_key), node_type, feature_types, combo
            )
            setattr(new_data, label_key, transformed_label)

        return new_data

    def create_collate_fn(self, augment: bool = True):
        """Create a collate function, optionally applying symmetry augmentation.

        INPUT:
        - augment: If True each sample is transformed by a randomly sampled
          group element; if False samples are only batched (validation/testing).
        """

        def collate_fn(data: list[HeteroDataBatch]) -> HeteroDataBatch:
            data_list = self.expand_data(data) if augment else data
            return cast(
                HeteroDataBatch,
                Batch.from_data_list(cast(list[Any], data_list)),
            )

        return collate_fn
