from typing import Self

import torch

from src.config.batch_schema import HeteroDataBatch
from src.config.train_enum import SymmetryType
from src.graph.feature.base_feature import BaseFeatureType
from src.graph.spec.base_spec import symmetry_permutation_dict_type
from src.graph.symmetry.base_symmetry import BaseSymmetry, symmetry_edge_dict_type


class K4Symmetry(BaseSymmetry):
    def __init__(
        self,
        symmetry_edge_dict: symmetry_edge_dict_type,
        symmetry_permutation_dict: symmetry_permutation_dict_type | None = None,
    ):
        """Initialize K4 symmetry."""
        super().__init__()
        self.symmetry_edge_dict = symmetry_edge_dict
        self.symmetry_edge_types = symmetry_edge_dict[SymmetryType.K4.value]
        self.symmetry_permutation = (
            symmetry_permutation_dict.get(SymmetryType.K4.value, {})
            if symmetry_permutation_dict is not None
            else {}
        )
        self.combination = self.generate_combination(self.symmetry_edge_types)
        self.reflection_coefficients = self.generate_reflection_coefficients(
            self.symmetry_edge_types
        )

    @classmethod
    def build_from(
        cls,
        symmetry_edge_dict: symmetry_edge_dict_type,
        symmetry_permutation_dict: symmetry_permutation_dict_type | None = None,
    ) -> Self:
        """Build K4 symmetry instance from configuration."""
        if SymmetryType.K4.value not in symmetry_edge_dict.keys():
            raise ValueError(
                f"The symmetry type does not match with configuration. Expected key: {SymmetryType.K4.value}"
            )
        return cls(symmetry_edge_dict, symmetry_permutation_dict)

    def expand_data(self, data_list: list[HeteroDataBatch]) -> list[HeteroDataBatch]:
        """
        Expand input data list according to K4 symmetry.

        INPUT:
        - data_list: list of input data items containing node features, edge features, etc.

        OUTPUT:
        - expanded_data_list: new list where each data item has been duplicated and transformed
          according to K4 symmetry.
        """
        expanded_data_list: list[HeteroDataBatch] = []
        for data in data_list:
            transformed_data = self._apply_k4_transform(data)
            expanded_data_list.append(transformed_data)

        return expanded_data_list

    def _apply_k4_transform(self, data: HeteroDataBatch) -> HeteroDataBatch:
        """
        Apply K4 transformations to the input data.

        This method should implement the specific transformations needed to create the K4 symmetry.
        For example, it might involve swapping node features and edge features according to the
        combinations generated by _generate_combination().

        INPUT:
        - data: input data item containing node features, edge features, etc. that needs to be transformed

        OUTPUT:
        - Transformed data with K4 symmetry applied in x_dict
        """
        new_data = data.clone()
        serialized_layout = getattr(data, "feature_type_layout", None)
        new_data.x_dict = self._modify_x_dict(data.x_dict, serialized_layout)

        available_edges = list(self.symmetry_edge_types.keys())
        canonical_combo = tuple(available_edges)

        if hasattr(new_data, "y_contact"):
            new_data.y_contact = self.apply_output_permutation(
                new_data.y_contact, "foot", canonical_combo
            )
        if hasattr(new_data, "y_ground_reaction_force"):
            new_data.y_ground_reaction_force = self.apply_output_permutation(
                new_data.y_ground_reaction_force, "foot", canonical_combo
            )
        return new_data

    def _modify_x_dict(
        self,
        x_dict: dict[str, torch.Tensor],
        serialized_layout: dict[str, list[tuple[int, int, str]]] | None,
    ) -> dict[str, torch.Tensor]:
        modified_x_dict: dict[str, torch.Tensor] = {}
        parsed_layout = self.parse_feature_type_layout(serialized_layout)
        if not parsed_layout:
            parsed_layout = self.infer_feature_type_layout(x_dict)

        available_edges = list(self.symmetry_edge_types.keys())
        canonical_combo = tuple(available_edges)

        for node_type, x in x_dict.items():
            blocks = parsed_layout.get(node_type)
            if blocks is None:
                blocks = self.infer_feature_type_layout({node_type: x}).get(
                    node_type, []
                )

            transformed = self.apply_row_permutation_combo(
                x.clone(), node_type, canonical_combo
            )
            for start, end, feature_type in blocks:
                if end <= start or feature_type == BaseFeatureType.SCALAR:
                    continue

                width = end - start
                if width % 3 != 0:
                    continue

                coeff = torch.ones(3, dtype=x.dtype, device=x.device)
                for sym_edge_type in canonical_combo:
                    edge_axes = self.symmetry_edge_types[sym_edge_type]
                    edge_coeff_tuple = self._coefficients_from_axes(
                        edge_axes, feature_type
                    )
                    edge_coeff = torch.tensor(
                        edge_coeff_tuple,
                        dtype=x.dtype,
                        device=x.device,
                    )
                    coeff = coeff * edge_coeff

                for offset in range(start, end, 3):
                    transformed[:, offset : offset + 3] = (
                        transformed[:, offset : offset + 3] * coeff
                    )

            if node_type == "base":
                base_versions = [x]
                for combo in self.combination:
                    if len(combo) == 0:
                        continue
                    base_transformed = self.apply_row_permutation_combo(
                        x.clone(), node_type, combo
                    )
                    for start, end, feature_type in blocks:
                        if end <= start or feature_type == BaseFeatureType.SCALAR:
                            continue

                        width = end - start
                        if width % 3 != 0:
                            continue

                        coeff = torch.ones(3, dtype=x.dtype, device=x.device)
                        for sym_edge_type in combo:
                            edge_axes = self.symmetry_edge_types[sym_edge_type]
                            edge_coeff_tuple = self._coefficients_from_axes(
                                edge_axes, feature_type
                            )
                            edge_coeff = torch.tensor(
                                edge_coeff_tuple,
                                dtype=x.dtype,
                                device=x.device,
                            )
                            coeff = coeff * edge_coeff

                        for offset in range(start, end, 3):
                            base_transformed[:, offset : offset + 3] = (
                                base_transformed[:, offset : offset + 3] * coeff
                            )

                    base_versions.append(base_transformed)

                modified_x_dict[node_type] = torch.cat(base_versions, dim=0)
            else:
                modified_x_dict[node_type] = transformed

        return modified_x_dict


BaseSymmetry.register(SymmetryType.K4)(K4Symmetry)  # type: ignore[arg-type]
